spring:
  profiles:
    active: "@spring.profile@"



  hateoas:
    use-hal-as-default-json-media-type: false

  jackson:
    time-zone: America/Sao_Paulo
    default-property-inclusion: NON_ABSENT
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true

  mail:
    brevo:
      mail:
        from: treinamaisapp@gmail.com


  # ✅ Flyway padrão (vale pra local e prd)
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    schemas: public
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate  # ✅ não deixe update em prd
    open-in-view: false  # opcional, mas recomendado
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true

  web:
    locale: pt_BR
    resources:
      add-mappings: true



  main:
    banner-mode: "off"

springdoc:
  swagger-ui:
    path: swagger
    use-root-path: true

security:
  jwt:
    secret: ${JWT_SECRET}

app:
  version: "@project.version@"
  name: "@project.name@"
  description: "@project.description@"

server:
  servlet:
    context-path: /treinamais-api

brevo:
  api:
    key: ${BREVO_API_KEY:}

# ==========================================================
# PRD
# ==========================================================
---
spring:
  config:
    activate:
      on-profile: prd


  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariTreinaMais
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 120000
      max-lifetime: 300000
      connection-timeout: 30000
      keepalive-time: 60000
      validation-timeout: 5000
      leak-detection-threshold: 60000

mercadopago:
  access-token: ${MP_ACCESS_TOKEN_SANDBOX}
  public-key: ${MP_PUBLIC_KEY_SANDBOX}
  webhook-url: "https://treinamaisapi.onrender.com/treinamais-api/api/comprar/pix"

ambiente:
  nmAmbiente: PRODUÇÃO

# ==========================================================
# DEV (se você usar)
# ==========================================================
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

ambiente:
  nmAmbiente: DESENVOLVIMENTO

# ==========================================================
# LOCAL
# ==========================================================
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      register-mbeans: true
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 120000
      max-lifetime: 300000
      connection-timeout: 30000
      keepalive-time: 60000

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mercadopago:
  access-token: ${MP_ACCESS_TOKEN_SANDBOX}
  public-key: ${MP_PUBLIC_KEY_SANDBOX}
  webhook-url: "https://treinamaisapi.onrender.com/treinamais-api/api/comprar/pix"

ambiente:
  nmAmbiente: DESENVOLVIMENTO-HML

logging:
  level:
    root: info
    org:
      springframework:
        kafka: error
    apache:
      kafka:
        clients:
          NetworkClient: error

server:
  port: 8094
