CREATE TABLE app_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_name VARCHAR(20) NOT NULL,
    version_code INT NOT NULL,
    apk_url VARCHAR(255) NOT NULL,
    description TEXT,
    force_update BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_app_version_code
ON app_version (version_code DESC);

INSERT INTO app_version (
    version_name,
    version_code,
    apk_url,
    description,
    force_update
) VALUES (
    '1.0.0',
    1,
    'https://treinamais.com/app/treinamais.apk',
    'Primeira versão do aplicativo',
    false
);